"""Creates default site files when running in an empty directory."""
import os, json

SITE_DIR = None


def _path(*parts):
    return os.path.join(SITE_DIR, *parts)


TEMPLATE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{TITLE}}</title>
{{FONT_LINK}}
  <link rel="stylesheet" href="{{STYLE_PATH}}">
</head>
<body>
  <header>
    <button class="sidebar-toggle" onclick="toggleSidebar()">&#9776;</button>
    <h1><a href="{{HOME_PATH}}">{{SITE_TITLE}}</a></h1>
{{THEME_TOGGLE}}
  </header>
  <div class="layout">
    <aside class="sidebar" id="sidebar">
{{SIDEBAR}}
    </aside>
    <main>
{{CONTENT}}
    </main>
{{COMMENTS}}
  </div>
  <script>
    function toggleSidebar() {
      document.getElementById('sidebar').classList.toggle('open');
    }
    function toggleCategory(header) {
      header.classList.toggle('active');
      header.querySelector('.arrow').classList.toggle('open');
      header.nextElementSibling.classList.toggle('open');
    }
  </script>
  <script>
    function toggleTheme() {
      document.body.classList.toggle('dark-mode');
      var b = document.body.classList.contains('dark-mode');
      localStorage.setItem('theme', b ? 'dark' : 'light');
      document.querySelector('.theme-toggle').textContent = b ? '\\u{1F319}' : '\\u2600\\uFE0F';
    }
    (function() {
      var btn = document.querySelector('.theme-toggle');
      if (localStorage.getItem('theme') === 'dark') {
        document.body.classList.add('dark-mode');
        if (btn) btn.textContent = '\\u{1F319}';
      }
    })();
  </script>
</body>
</html>"""

DEFAULT_CSS = """/* Auto-generated by Site Tools. Edit via Theme Customizer tab. */
:root {
  --body-bg: #1e1e1e; --text: #e0e0e0; --hero-bg: #1e1e1e;
  --card-bg: #2a2a2a; --card-border: #333; --input-bg: #2a2a2a; --input-border: #444;
  --label: #e0e0e0; --muted: #888;
  --accent: #4a9eff; --accent-hover: #3a7acc; --accent-text: #fff;
  --dark-body-bg: #121212; --dark-text: #e0e0e0; --dark-hero-bg: #121212;
  --dark-card-bg: #1e1e1e; --dark-card-border: #333;
  --dark-input-bg: #2a2a2a; --dark-input-border: #444;
  --dark-label: #e0e0e0; --dark-muted: #888;
  --dark-accent: #4a9eff; --dark-accent-hover: #3a7acc; --dark-accent-text: #fff;
  --header-bg: #1e1e1e; --header-text: #eee;
  --sidebar-bg: #2a2a2a; --sidebar-text: #eee; --sidebar-border: #333;
  --sidebar-hover: #333; --link-muted: #888; --link-hover-text: #eee;
  --avatar-border: #555; --footer-bg: #1e1e1e; --footer-text: #eee;
  --theme-border: #555;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Noto Sans Bengali', system-ui, sans-serif; background: var(--body-bg); color: var(--text); min-height: 100vh; display: flex; flex-direction: column; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
header { background: var(--header-bg); color: var(--header-text); padding: 0.75rem 1rem; display: flex; align-items: center; gap: 0.75rem; }
header h1 { flex: 1; font-size: 1.15rem; }
header h1 a { color: inherit; }
header h1 a:hover { text-decoration: none; }
.sidebar-toggle, .theme-toggle { background: none; border: none; color: var(--header-text); font-size: 1.3rem; cursor: pointer; padding: 4px 8px; border-radius: 4px; }
.sidebar-toggle:hover, .theme-toggle:hover { background: var(--sidebar-hover); }
.layout { display: flex; flex: 1; }
.sidebar { width: 220px; background: var(--sidebar-bg); border-right: 1px solid var(--sidebar-border); flex-shrink: 0; display: flex; flex-direction: column; transition: transform 0.3s; position: sticky; top: 0; height: 100vh; overflow-y: auto; }
.sidebar.open { transform: translateX(0); }
.sidebar-top { display: flex; justify-content: space-between; align-items: center; padding: 1rem; border-bottom: 1px solid var(--sidebar-border); }
.sidebar-top h2 { font-size: 0.9rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.5px; }
.close-btn { background: none; border: none; color: var(--muted); font-size: 1.5rem; cursor: pointer; }
.sidebar-owner { padding: 1.25rem 1rem; text-align: center; border-bottom: 1px solid var(--sidebar-border); }
.owner-avatar { width: 60px; height: 60px; border-radius: 50%; object-fit: cover; margin-bottom: 0.6rem; border: 2px solid var(--avatar-border); }
.owner-name { font-size: 1rem; font-weight: 700; color: var(--sidebar-text); margin-bottom: 0.25rem; }
.owner-title { font-size: 0.85rem; color: var(--accent); margin-bottom: 0.25rem; }
.owner-bio { font-size: 0.8rem; color: var(--link-muted); }
.category { border-bottom: 1px solid var(--sidebar-border); }
.category-header { padding: 0.75rem 1rem; cursor: pointer; display: flex; justify-content: space-between; align-items: center; color: var(--sidebar-text); font-weight: 600; font-size: 0.9rem; transition: background 0.2s; }
.category-header:hover { background: var(--sidebar-hover); }
.arrow { font-size: 0.7rem; transition: transform 0.2s; }
.arrow.open { transform: rotate(90deg); }
.sub-links { list-style: none; max-height: 0; overflow: hidden; transition: max-height 0.3s ease; }
.sub-links.open { max-height: 500px; }
.sub-links li a { display: block; padding: 0.4rem 1rem 0.4rem 2rem; color: var(--link-muted); font-size: 0.85rem; }
.sub-links li a:hover { color: var(--link-hover-text); background: var(--sidebar-hover); }
main { flex: 1; padding: 1.25rem; max-width: 860px; margin: 0 auto; width: 100%; }
.doc-content { padding-right: 0.5rem; }
.doc-content img, .doc-content table, .doc-content pre, .doc-content div { max-width: 100%; overflow-x: auto; }
.owner-card { text-align: center; }
.owner-card-avatar { width: 80px; height: 80px; border-radius: 50%; object-fit: cover; border: 3px solid var(--avatar-border); margin-bottom: 0.75rem; }
.owner-card-name { font-size: 1.2rem; font-weight: 700; color: var(--label); }
.owner-card-title { font-size: 0.95rem; color: var(--accent); margin-top: 0.2rem; }
.owner-card-bio { font-size: 0.85rem; color: var(--muted); margin-top: 0.3rem; line-height: 1.4; }
.owner-card-contacts { display: flex; flex-wrap: wrap; justify-content: center; gap: 0.5rem 1rem; margin-top: 0.75rem; }
.owner-contact-link { color: var(--accent); font-size: 0.85rem; text-decoration: none; padding: 0.2rem 0.4rem; border-radius: 4px; transition: background 0.2s; }
.owner-contact-link:hover { background: var(--card-border); text-decoration: underline; }
.home-hero { text-align: center; padding: 1rem 1rem 1.5rem; }
.home-hero h1 { font-size: 2rem; margin-bottom: 0.5rem; }
.home-tagline { color: var(--muted); font-size: 1rem; }
.home-sections { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1.25rem; max-width: 800px; margin: 1.5rem auto; padding: 0 1rem; }
.home-card { background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 8px; padding: 1rem 1.25rem; }
.home-card h2 { font-size: 1rem; margin-bottom: 0.5rem; color: var(--label); }
.home-card ul { list-style: none; }
.home-card li { margin: 4px 0; }
.home-card li a { font-size: 0.9rem; }
footer { text-align: center; padding: 1rem; color: var(--footer-text); font-size: 0.8rem; border-top: 1px solid var(--card-border); margin-top: auto; }
#comments-section { max-width: 600px; margin: 2rem auto; padding: 0 1rem; }
#comments-section h3 { margin-bottom: 0.75rem; font-size: 1.1rem; }
#comment-form { display: flex; flex-direction: column; gap: 0.5rem; }
#comment-form input, #comment-form textarea { background: var(--input-bg); color: var(--text); border: 1px solid var(--input-border); border-radius: 6px; padding: 8px; font-size: 0.9rem; }
#comment-form button { background: var(--accent); color: var(--accent-text); border: none; border-radius: 6px; padding: 8px 16px; cursor: pointer; align-self: flex-start; }
#comment-form button:hover { background: var(--accent-hover); }
.comment { background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 6px; padding: 10px; margin-bottom: 8px; }
.comment .name { font-weight: 700; font-size: 0.9rem; }
.comment .date { color: var(--muted); font-size: 0.75rem; margin-left: 6px; }
.comment .body { margin-top: 4px; font-size: 0.9rem; }
@media (max-aspect-ratio: 1/1) { #comment-form, #comments-list { display: flex; flex-direction: column; } }
"""

DEFAULT_CONFIG = {
    "supabase_url": "",
    "supabase_anon_key": "",
    "comments_enabled": True,
    "git_remote_url": "",
    "git_user_name": "",
    "git_user_email": "",
    "git_commit_message": "update site via generator",
    "git_auto_push": True,
    "owner_name": "",
    "owner_bio": "",
    "owner_avatar": "",
    "owner_title": "",
    "owner_contacts": [],
    "site_title": "My Site",
    "gui_theme": "Dark",
    "custom_font_url": "",
    "custom_font_family": "",
    "gui_font_size": 14,
}


def ensure_site_files(site_dir):
    global SITE_DIR
    SITE_DIR = site_dir
    created = []

    def check(path, content, mode="w"):
        if not os.path.exists(path):
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, mode, encoding="utf-8") as f:
                f.write(content)
            created.append(os.path.basename(path))

    check(_path("template.html"), TEMPLATE_HTML)
    check(_path("style.css"), DEFAULT_CSS)

    if not os.path.exists(_path("config.json")):
        with open(_path("config.json"), "w", encoding="utf-8") as f:
            json.dump(DEFAULT_CONFIG, f, indent=2)
        created.append("config.json")

    if not os.path.exists(_path("config.local.json")):
        with open(_path("config.local.json"), "w", encoding="utf-8") as f:
            json.dump({"github_token": ""}, f, indent=2)
        created.append("config.local.json")

    check(_path(".nojekyll"), "")

    old_ref = _path("template reference.txt")
    if os.path.exists(old_ref):
        os.remove(old_ref)

    sidebar_path = _path("sidebar.json")
    if not os.path.exists(sidebar_path):
        import sidebar_util
        sidebar_util.SITE_DIR = site_dir
        created.append("sidebar.json")
        sidebar_util.init_from_filesystem()

    return created
